[chat]
model = "gpt-4o-mini"
end_point = "https://api.openai.com/v1/chat/completions"
system_message = "You are a helpful assistant."


[general]
top_k = 3
agent_name = "agent_1"
look_back_window_size = 7
trading_symbol = "TSLA"
character_string = ""


[agent.agent_1.embedding.detail]
embedding_model = "text-embedding-ada-002"
chunk_size=5000
verbose=false


[short]
importance_score_initialization = "sample"
decay_params = {recency_factor=3.0, importance_factor=0.92}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
jump_threshold_upper = 60

[mid]
jump_threshold_lower = 60
jump_threshold_upper = 80 
importance_score_initialization = "sample"
decay_params = {recency_factor=90.0, importance_factor=0.967}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}

[long]
jump_threshold_lower = 80
importance_score_initialization = "sample"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}

[reflection]
importance_score_initialization = "sample"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
